name: "Test Action"
description: "Grabs your input and publishes it as GitHub Pages website"
author: "Test"
inputs:

  github_pages_branch:
    description: "The branch to publish the output to, default is 'gh-pages'"
    default: gh-pages
  blog_directory:
    description: "The directory containing your blogs (yaml), default is '_blogs'"
    default: _blogs
runs:
  using: "composite"
  steps:
    # Checkout the blog content to a specific folder
    - uses: actions/checkout@v3
      with:
        path: 'blog-content'

    # Checkout the wasm-blog-engine to the root folder
    - uses: actions/checkout@v3
      with:
        repository: 'NielsNijveldt/TestAction'

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: ${{ inputs.github_pages_branch }}
        folder: '/release/wwwroot'
        repository-name: ${{ github.repository }}